### PR TITLE
Apple PKPass Boarding Pass Schema

### PR DESCRIPTION
**Pull request by georgejpadayatti**
Signed-off-by: George J Padayatti <george.padayatti@igrant.io>

### CODE REVIEW

**Review by lalc — COMMENTED** [review]
What is the duplicate key check?

**Comment by georgejpadayatti** [comment]
> What is the duplicate key check?

Can't identify a field for the same. Any suggestions ?

**Comment by josmilan** [comment]
PKPASS BoardingPass Passport Nationality, PKPASS BoardingPass Residence   is not available

PKPASS BoardingPass Class  is repeated

PKPASS BoardingPass Boarding Date is sometime joint with boarding time

**Comment by georgejpadayatti** [comment]
> PKPASS BoardingPass Passport Nationality, PKPASS BoardingPass Residence is not available

I will remove them.

> PKPASS BoardingPass Class is repeated

Noted.

> PKPASS BoardingPass Boarding Date is sometime joint with boarding time

Add an empty space, if data is not available. ?

**Comment by georgejpadayatti** [comment]
> PKPASS BoardingPass Passport Nationality, PKPASS BoardingPass Residence is not available
> 
> PKPASS BoardingPass Class is repeated
> 
> PKPASS BoardingPass Boarding Date is sometime joint with boarding time

✅

**Comment by georgejpadayatti** [comment]
@rebink Have made the changes as @josmilan requested. Can you check if this is ok and approve the PR ?

**Review by rebink — APPROVED** [review]

**Pull request merged**
