### PR TITLE
Feature/malaysian vaccine card support

### PR DESCRIPTION
**Pull request by snehagrawal98**

### CODE REVIEW

**Review by georgejpadayatti — APPROVED** [review]

**Review by lalc — CHANGES_REQUESTED** [review]
Please see if you can find references where you can see the attribute names.

@georgejpadayatti Is there any easier way to get the attributes names from the QR code? For example, I think you could consider renaming the Member State to Country as it's not a member state.

**Comment by georgejpadayatti** [comment]
Looks perfect. Please note the following comments:

1. The change could have been a single commit.
2. Country code for Malaysia is mys

**Comment by georgejpadayatti** [comment]
> Please see if you can find references where you can see the attribute names.
> 
> 
> 
> @georgejpadayatti Is there any easier way to get the attributes names from the QR code? For example, I think you could consider renaming the Member State to Country as it's not a member state. 

That is ideal. But QR codes in most cases would be using abbreviations for obvious reasons (to reduce length).

**Comment by georgejpadayatti** [comment]
> Please see if you can find references where you can see the attribute names.
> 
> 
> 
> @georgejpadayatti Is there any easier way to get the attributes names from the QR code? For example, I think you could consider renaming the Member State to Country as it's not a member state. 

Remember the data schema we are providing is iGrant.io standardised schema. Its not the original schema of the QR code.

**Comment by lalc** [comment]
@snehagrawal98 Please make these changes:
1) The attribute name to "Country" from "Member State"
2) Update the README file in the parent folder and add link to Malaysia.

**Review by lalc — APPROVED** [review]

**Pull request merged**
